// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGJUAvifsZOTOsmyZwUEo9kYX5wsOf8lQ',
    appId: '1:398513095158:web:1d29a7cf7c548d4552c7d7',
    messagingSenderId: '398513095158',
    projectId: 'mind-flip-42dc6',
    authDomain: 'mind-flip-42dc6.firebaseapp.com',
    storageBucket: 'mind-flip-42dc6.firebasestorage.app',
    measurementId: 'G-X45X1MJ1RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoLHCiYVUFNmcWBa18KtUogFtHD-8cHmA',
    appId: '1:398513095158:android:f3cbdd9b7d21dd5952c7d7',
    messagingSenderId: '398513095158',
    projectId: 'mind-flip-42dc6',
    storageBucket: 'mind-flip-42dc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMaqY8PYgJcThR8vfEKfGhRxkTlzZXS80',
    appId: '1:398513095158:ios:0943bf1c6a95fa5552c7d7',
    messagingSenderId: '398513095158',
    projectId: 'mind-flip-42dc6',
    storageBucket: 'mind-flip-42dc6.firebasestorage.app',
    iosBundleId: 'com.example.mindFlip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMaqY8PYgJcThR8vfEKfGhRxkTlzZXS80',
    appId: '1:398513095158:ios:0943bf1c6a95fa5552c7d7',
    messagingSenderId: '398513095158',
    projectId: 'mind-flip-42dc6',
    storageBucket: 'mind-flip-42dc6.firebasestorage.app',
    iosBundleId: 'com.example.mindFlip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGJUAvifsZOTOsmyZwUEo9kYX5wsOf8lQ',
    appId: '1:398513095158:web:0c6e835db8deea8a52c7d7',
    messagingSenderId: '398513095158',
    projectId: 'mind-flip-42dc6',
    authDomain: 'mind-flip-42dc6.firebaseapp.com',
    storageBucket: 'mind-flip-42dc6.firebasestorage.app',
    measurementId: 'G-JD5FC3D3CV',
  );
}
